CREATE TABLE Users (
    UserID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username TEXT CHARACTER SET utf8mb4,
    password TEXT CHARACTER SET utf8mb4,
    LastSeen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RegistrationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NumberOfPosts INT DEFAULT 0,
    NumberOfSubjects INT DEFAULT 0,
    HasAProfilePicture BOOLEAN DEFAULT FALSE
);


CREATE TABLE Subjects (
    SubjectID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    AuthorID INT NOT NULL,
    Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Title TEXT CHARACTER SET utf8mb4,
    NumberOfPosts INT DEFAULT 0,
    Content TEXT CHARACTER SET utf8mb4,
    LastPostID INT DEFAULT 0
);


CREATE TABLE Posts (
    PostID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    AuthorID INT NOT NULL,
    PostContent TEXT CHARACTER SET utf8mb4,
    SubjectID INT NOT NULL,
    Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
